quarkus.datasource.db-kind=
quarkus.datasource.username=
quarkus.datasource.password=
quarkus.datasource.jdbc.url=
quarkus.datasource.jdbc.min-size=5
quarkus.datasource.jdbc.max-size=20

quarkus.hibernate-orm.database.generation=none

quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migration

quarkus.log.category."com.aiperson.service".level=DEBUG
quarkus.log.category."org.hibernate.SQL".level=DEBUG